2017-05-12 17:09:06 [scrapy] INFO: Scrapy 1.0.3 started (bot: lianjia)
2017-05-12 17:09:06 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-05-12 17:09:06 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'lianjia.spiders', 'SPIDER_MODULES': ['lianjia.spiders'], 'BOT_NAME': 'lianjia', 'DOWNLOAD_TIMEOUT': 10, 'COOKIES_ENABLED': False, 'DOWNLOAD_DELAY': 3}
2017-05-12 17:09:07 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2017-05-12 17:09:07 [boto] DEBUG: Retrieving credentials from metadata server.
2017-05-12 17:09:08 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2017-05-12 17:09:08 [boto] ERROR: Unable to read instance data, giving up
2017-05-12 17:09:08 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, HttpProxyMiddleware, RetryMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-05-12 17:09:08 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2017-05-12 17:09:08 [scrapy] INFO: Enabled item pipelines: MySQLStoreCnblogsPipeline
2017-05-12 17:09:08 [scrapy] INFO: Spider opened
2017-05-12 17:09:08 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2017-05-12 17:09:08 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6029
2017-05-12 17:09:08 [lianjia.HttpProxyMiddleware] DEBUG: None 302 http://bj.lianjia.com/ershoufang/
2017-05-12 17:09:08 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:09:08 [lianjia.HttpProxyMiddleware] INFO: now using new proxy: http://112.17.14.19:8080
2017-05-12 17:09:12 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.19:8080 302 http://bj.lianjia.com/ershoufang/
2017-05-12 17:09:12 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:09:12 [lianjia.HttpProxyMiddleware] INFO: invalidate {'count': 1, 'valid': True, 'proxy': 'http://112.17.14.19:8080'}
2017-05-12 17:09:12 [lianjia.HttpProxyMiddleware] INFO: now using new proxy: http://116.211.143.11:80
2017-05-12 17:09:12 [lianjia.HttpProxyMiddleware] INFO: dumping proxyes to file
2017-05-12 17:09:17 [scrapy] DEBUG: Retrying <GET http://bj.lianjia.com/ershoufang/> (failed 1 times): 500 Internal Server Error
2017-05-12 17:09:21 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 200 http://bj.lianjia.com/ershoufang/
2017-05-12 17:09:21 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/> (referer: None)
2017-05-12 17:09:24 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 200 http://bj.lianjia.com/ershoufang/101101549005.html
2017-05-12 17:09:24 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101549005.html> (referer: http://bj.lianjia.com/ershoufang/)
2017-05-12 17:09:26 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101549005.html>
{'area': u'\u660c\u5e73 \u56de\u9f99\u89c2',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5546\u54c1\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u6df7\u5408\u7ed3\u6784',
 'community': u'\u9f99\u534e\u56ed',
 'elevator': u'\u65e0',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u5e95\u5c42 (\u51716\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'89.6\u33a1',
 'in_area': u'\u6682\u65e0\u6570\u636e',
 'latitude': '116.332045,40.081334',
 'mortgage': u'\u65e0\u62b5\u62bc',
 'orient': u'\u5357 \u5317',
 'price': u'459',
 'scale': u'\u4e00\u68af\u4e24\u6237',
 'status': u'\u7b80\u88c5',
 'structure': u'\u6682\u65e0\u6570\u636e',
 'style': u'3\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-05-05',
 'trade': u'2005-10-27',
 'unit_price': u'51228',
 'url': 'http://bj.lianjia.com/ershoufang/101101549005.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:09:31 [scrapy] DEBUG: Retrying <GET http://bj.lianjia.com/ershoufang/101101491002.html> (failed 1 times): 500 Internal Server Error
2017-05-12 17:09:33 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 200 http://bj.lianjia.com/ershoufang/101101507109.html
2017-05-12 17:09:33 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101507109.html> (referer: http://bj.lianjia.com/ershoufang/)
2017-05-12 17:09:34 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 200 http://bj.lianjia.com/ershoufang/101101465080.html
2017-05-12 17:09:34 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101465080.html> (referer: http://bj.lianjia.com/ershoufang/)
2017-05-12 17:09:38 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 200 http://bj.lianjia.com/ershoufang/101101520723.html
2017-05-12 17:09:38 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101520723.html> (referer: http://bj.lianjia.com/ershoufang/)
2017-05-12 17:09:43 [scrapy] DEBUG: Retrying <GET http://bj.lianjia.com/ershoufang/101101026122.html> (failed 1 times): 500 Internal Server Error
2017-05-12 17:09:49 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 200 http://bj.lianjia.com/ershoufang/101101503018.html
2017-05-12 17:09:49 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101503018.html> (referer: http://bj.lianjia.com/ershoufang/)
2017-05-12 17:09:51 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 200 http://bj.lianjia.com/ershoufang/101101470476.html
2017-05-12 17:09:51 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101470476.html> (referer: http://bj.lianjia.com/ershoufang/)
2017-05-12 17:09:53 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 200 http://bj.lianjia.com/ershoufang/101101548078.html
2017-05-12 17:09:53 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101548078.html> (referer: http://bj.lianjia.com/ershoufang/)
2017-05-12 17:09:55 [scrapy] DEBUG: Retrying <GET http://bj.lianjia.com/ershoufang/101101477937.html> (failed 1 times): 500 Internal Server Error
2017-05-12 17:09:58 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101276533.html
2017-05-12 17:09:58 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:09:58 [lianjia.HttpProxyMiddleware] INFO: invalidate {'count': 28, 'valid': True, 'proxy': 'http://116.211.143.11:80'}
2017-05-12 17:09:58 [lianjia.HttpProxyMiddleware] INFO: now using new proxy: http://112.17.14.24:80
2017-05-12 17:10:03 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101260501.html
2017-05-12 17:10:03 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:08 [scrapy] INFO: Crawled 8 pages (at 8 pages/min), scraped 1 items (at 1 items/min)
2017-05-12 17:10:10 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101323760.html
2017-05-12 17:10:10 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:15 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101179403.html
2017-05-12 17:10:15 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:15 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101352915.html
2017-05-12 17:10:15 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:17 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101545121.html
2017-05-12 17:10:17 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:22 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/pg2/
2017-05-12 17:10:22 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:26 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101537313.html
2017-05-12 17:10:26 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:29 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101354577.html
2017-05-12 17:10:29 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:10:32 [twisted] CRITICAL: Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:10:32 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101520723.html>
{'area': u'\u660c\u5e73 \u56de\u9f99\u89c2',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5546\u54c1\u623f',
 'belongs': u'\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u6df7\u5408\u7ed3\u6784',
 'community': u'\u9f99\u534e\u56ed',
 'elevator': u'\u65e0',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u4e2d\u697c\u5c42 (\u51717\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'109.8\u33a1',
 'in_area': u'\u6682\u65e0\u6570\u636e',
 'latitude': '116.332045,40.081334',
 'mortgage': u'\u6709\u62b5\u62bc \u5ba2\u6237\u507f\u8fd8',
 'orient': u'\u5357 \u5317',
 'price': u'520',
 'scale': u'\u4e00\u68af\u4e24\u6237',
 'status': u'\u7cbe\u88c5',
 'structure': u'\u6682\u65e0\u6570\u636e',
 'style': u'3\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u5730\u94c1 \u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-04-27',
 'trade': u'2009-08-05',
 'unit_price': u'47359',
 'url': 'http://bj.lianjia.com/ershoufang/101101520723.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:10:32 [twisted] CRITICAL: Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:10:32 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101548078.html>
{'area': u'\u6d77\u6dc0 \u7518\u5bb6\u53e3',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5546\u54c1\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u6df7\u5408\u7ed3\u6784',
 'community': u'\u961c\u5317\u5c0f\u533a',
 'elevator': u'\u65e0',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u4e2d\u697c\u5c42 (\u51715\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'56.27\u33a1',
 'in_area': u'42.6\u33a1',
 'latitude': '116.340299,39.929294',
 'mortgage': u'\u6682\u65e0\u6570\u636e',
 'orient': u'\u5357 \u5317',
 'price': u'588',
 'scale': u'\u4e00\u68af\u4e09\u6237',
 'status': u'\u5176\u4ed6',
 'structure': u'\u5e73\u5c42',
 'style': u'2\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u5730\u94c1 \u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-05-05',
 'trade': u'2011-07-04',
 'unit_price': u'104496',
 'url': 'http://bj.lianjia.com/ershoufang/101101548078.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:10:32 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101304930.html
2017-05-12 17:10:32 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:35 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101173465.html
2017-05-12 17:10:35 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:38 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101507109.html>
{'area': u'\u901a\u5dde \u4e5d\u68f5\u6811(\u5bb6\u4e50\u798f)',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5546\u54c1\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u5854\u7ed3\u5408',
 'building_style': u'\u94a2\u6df7\u7ed3\u6784',
 'community': u'\u9753\u666f\u660e\u5c45',
 'elevator': u'\u6709',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u4e2d\u697c\u5c42 (\u517112\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'105.33\u33a1',
 'in_area': u'88.81\u33a1',
 'latitude': '116.643924,39.889841',
 'mortgage': u'\u65e0\u62b5\u62bc',
 'orient': u'\u5357 \u5317',
 'price': u'600',
 'scale': u'\u4e00\u68af\u4e24\u6237',
 'status': u'\u7b80\u88c5',
 'structure': u'\u6682\u65e0\u6570\u636e',
 'style': u'2\u5ba42\u53851\u53a82\u536b',
 'tag': u'\u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-04-23',
 'trade': u'2005-12-22',
 'unit_price': u'56964',
 'url': 'http://bj.lianjia.com/ershoufang/101101507109.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:10:40 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101465080.html>
{'area': u'\u671d\u9633 \u5065\u7fd4\u6865',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5df2\u8d2d\u516c\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u6df7\u5408\u7ed3\u6784',
 'community': u'\u534e\u4e25\u5317\u91cc\u5c0f\u533a',
 'elevator': u'\u65e0',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u9876\u5c42 (\u51716\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'49.39\u33a1',
 'in_area': u'34.13\u33a1',
 'latitude': '116.390213,39.989129',
 'mortgage': u'\u65e0\u62b5\u62bc',
 'orient': u'\u4e1c\u5357',
 'price': u'410',
 'scale': u'\u4e00\u68af\u56db\u6237',
 'status': u'\u7b80\u88c5',
 'structure': u'\u6682\u65e0\u6570\u636e',
 'style': u'1\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-04-12',
 'trade': u'2003-10-15',
 'unit_price': u'83013',
 'url': 'http://bj.lianjia.com/ershoufang/101101465080.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:10:41 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101114188.html
2017-05-12 17:10:41 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:43 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101047743.html
2017-05-12 17:10:43 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:45 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101523851.html
2017-05-12 17:10:45 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:52 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101520656.html
2017-05-12 17:10:52 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:54 [lianjia.HttpProxyMiddleware] DEBUG: http://116.211.143.11:80 302 http://bj.lianjia.com/ershoufang/101101519442.html
2017-05-12 17:10:54 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:54 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101503018.html>
{'area': u'\u6d77\u6dc0 \u7518\u5bb6\u53e3',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u79c1\u4ea7',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u6df7\u5408\u7ed3\u6784',
 'community': u'\u589e\u5149\u8def43\u53f7\u9662',
 'elevator': u'\u65e0',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u4f4e\u697c\u5c42 (\u51716\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'61.1\u33a1',
 'in_area': u'43.1\u33a1',
 'latitude': '116.324868,39.934263',
 'mortgage': u'\u65e0\u62b5\u62bc',
 'orient': u'\u5357 \u5317',
 'price': u'640',
 'scale': u'\u4e00\u68af\u4e09\u6237',
 'status': u'\u7cbe\u88c5',
 'structure': u'\u5e73\u5c42',
 'style': u'2\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u5730\u94c1 \u623f\u672c\u6ee1\u4e94\u5e74',
 'taxtext': '',
 'time': u'2017-04-22',
 'trade': u'2009-01-21',
 'unit_price': u'104746',
 'url': 'http://bj.lianjia.com/ershoufang/101101503018.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:10:56 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101276533.html
2017-05-12 17:10:56 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:10:56 [lianjia.HttpProxyMiddleware] INFO: invalidate {'count': 16, 'valid': True, 'proxy': 'http://112.17.14.24:80'}
2017-05-12 17:10:56 [lianjia.HttpProxyMiddleware] INFO: now using new proxy: http://112.17.14.43:80
2017-05-12 17:10:56 [lianjia.HttpProxyMiddleware] INFO: dumping proxyes to file
2017-05-12 17:10:56 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101470476.html>
{'area': u'\u901a\u5dde \u5317\u5173',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5546\u54c1\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u6df7\u5408\u7ed3\u6784',
 'community': u'\u897f\u6f5e\u82d1\u5c0f\u533a',
 'elevator': u'\u65e0',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u4e2d\u697c\u5c42 (\u51716\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'75.66\u33a1',
 'in_area': u'\u6682\u65e0\u6570\u636e',
 'latitude': '116.667038,39.942451',
 'mortgage': u'\u6709\u62b5\u62bc 28\u4e07\u5143 \u4e2d\u4fe1\u94f6\u884c \u5ba2\u6237\u507f\u8fd8',
 'orient': u'\u5357 \u5317',
 'price': u'385',
 'scale': u'\u4e00\u68af\u4e24\u6237',
 'status': u'\u7b80\u88c5',
 'structure': u'\u6682\u65e0\u6570\u636e',
 'style': u'2\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u623f\u672c\u6ee1\u4e94\u5e74',
 'taxtext': '',
 'time': u'2017-04-13',
 'trade': u'2010-02-02',
 'unit_price': u'50886',
 'url': 'http://bj.lianjia.com/ershoufang/101101470476.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:11:00 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101260501.html
2017-05-12 17:11:00 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:05 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101323760.html
2017-05-12 17:11:05 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:06 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101179403.html
2017-05-12 17:11:06 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:08 [scrapy] INFO: Crawled 8 pages (at 0 pages/min), scraped 7 items (at 6 items/min)
2017-05-12 17:11:10 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101352915.html
2017-05-12 17:11:10 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:14 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101545121.html
2017-05-12 17:11:14 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:17 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/pg2/
2017-05-12 17:11:17 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:21 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101537313.html
2017-05-12 17:11:21 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:25 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101354577.html
2017-05-12 17:11:25 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:29 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101304930.html
2017-05-12 17:11:29 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:33 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101173465.html
2017-05-12 17:11:33 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:38 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101114188.html
2017-05-12 17:11:38 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:42 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101047743.html
2017-05-12 17:11:42 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:45 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101523851.html
2017-05-12 17:11:45 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:49 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101520656.html
2017-05-12 17:11:49 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:53 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.24:80 302 http://bj.lianjia.com/ershoufang/101101519442.html
2017-05-12 17:11:53 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:57 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101276533.html
2017-05-12 17:11:57 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:11:57 [lianjia.HttpProxyMiddleware] INFO: invalidate {'count': 16, 'valid': True, 'proxy': 'http://112.17.14.43:80'}
2017-05-12 17:11:57 [lianjia.HttpProxyMiddleware] INFO: now using new proxy: http://111.13.7.123:80
2017-05-12 17:11:57 [lianjia.HttpProxyMiddleware] INFO: dumping proxyes to file
2017-05-12 17:11:59 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101260501.html
2017-05-12 17:11:59 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:03 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101323760.html
2017-05-12 17:12:03 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:07 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101179403.html
2017-05-12 17:12:07 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:08 [scrapy] INFO: Crawled 8 pages (at 0 pages/min), scraped 7 items (at 0 items/min)
2017-05-12 17:12:11 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101352915.html
2017-05-12 17:12:11 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:15 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101545121.html
2017-05-12 17:12:15 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:17 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/pg2/
2017-05-12 17:12:17 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:21 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101537313.html
2017-05-12 17:12:21 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:24 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101354577.html
2017-05-12 17:12:24 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:28 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101304930.html
2017-05-12 17:12:28 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:32 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101173465.html
2017-05-12 17:12:32 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:36 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101114188.html
2017-05-12 17:12:36 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:40 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101047743.html
2017-05-12 17:12:40 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:44 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101523851.html
2017-05-12 17:12:44 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:47 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101520656.html
2017-05-12 17:12:47 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:51 [lianjia.HttpProxyMiddleware] DEBUG: http://112.17.14.43:80 302 http://bj.lianjia.com/ershoufang/101101519442.html
2017-05-12 17:12:51 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:12:56 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 200 http://bj.lianjia.com/ershoufang/101101276533.html
2017-05-12 17:12:56 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101276533.html> (referer: http://bj.lianjia.com/ershoufang/)
Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:12:56 [twisted] CRITICAL: Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:12:56 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101276533.html>
{'area': u'\u6d77\u6dc0 \u9a6c\u8fde\u6d3c',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5df2\u8d2d\u516c\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u7816\u6df7\u7ed3\u6784',
 'community': u'\u83ca\u56ed',
 'elevator': u'\u65e0',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u4e2d\u697c\u5c42 (\u51716\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'86.73\u33a1',
 'in_area': u'\u6682\u65e0\u6570\u636e',
 'latitude': '116.296408,40.039756',
 'mortgage': u'\u65e0\u62b5\u62bc',
 'orient': u'\u5357 \u5317',
 'price': u'670',
 'scale': u'\u4e00\u68af\u4e24\u6237',
 'status': u'\u7cbe\u88c5',
 'structure': u'\u5e73\u5c42',
 'style': u'3\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-03-04',
 'trade': u'1999-12-07',
 'unit_price': u'77251',
 'url': 'http://bj.lianjia.com/ershoufang/101101276533.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:12:59 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 200 http://bj.lianjia.com/ershoufang/101101260501.html
2017-05-12 17:12:59 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101260501.html> (referer: http://bj.lianjia.com/ershoufang/)
Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:12:59 [twisted] CRITICAL: Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:12:59 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101260501.html>
{'area': u'\u671d\u9633 \u8c46\u5404\u5e84',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5546\u54c1\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u94a2\u6df7\u7ed3\u6784',
 'community': u'\u5bcc\u529b\u53c8\u4e00\u57ceA\u533a',
 'elevator': u'\u6709',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u4f4e\u697c\u5c42 (\u517122\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'149.9\u33a1',
 'in_area': u'118.97\u33a1',
 'latitude': '116.572491,39.853078',
 'mortgage': u'\u65e0\u62b5\u62bc \u4e1a\u4e3b\u81ea\u8fd8',
 'orient': u'\u5357 \u5317',
 'price': u'810',
 'scale': u'\u4e24\u68af\u4e24\u6237',
 'status': u'\u7cbe\u88c5',
 'structure': u'\u5e73\u5c42',
 'style': u'3\u5ba42\u53851\u53a82\u536b',
 'tag': u'\u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-03-01',
 'trade': u'2009-12-25',
 'unit_price': u'54036',
 'url': 'http://bj.lianjia.com/ershoufang/101101260501.html',
 'warm': u'\u81ea\u4f9b\u6696'}
2017-05-12 17:13:02 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 200 http://bj.lianjia.com/ershoufang/101101323760.html
2017-05-12 17:13:02 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101323760.html> (referer: http://bj.lianjia.com/ershoufang/)
Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:02 [twisted] CRITICAL: Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:02 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101323760.html>
{'area': u'\u660c\u5e73 \u56de\u9f99\u89c2',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5546\u54c1\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u7816\u6df7\u7ed3\u6784',
 'community': u'\u5317\u4eac\u4eba\u5bb6',
 'elevator': u'\u65e0',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u9876\u5c42 (\u51716\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'74.22\u33a1',
 'in_area': u'65.22\u33a1',
 'latitude': '116.311776,40.084907',
 'mortgage': u'\u65e0\u62b5\u62bc',
 'orient': u'\u5357 \u5317',
 'price': u'445',
 'scale': u'\u4e00\u68af\u4e24\u6237',
 'status': u'\u7b80\u88c5',
 'structure': u'\u5e73\u5c42',
 'style': u'2\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-03-12',
 'trade': u'2007-08-24',
 'unit_price': u'59957',
 'url': 'http://bj.lianjia.com/ershoufang/101101323760.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:13:05 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 200 http://bj.lianjia.com/ershoufang/101101179403.html
2017-05-12 17:13:05 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101179403.html> (referer: http://bj.lianjia.com/ershoufang/)
Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:05 [twisted] CRITICAL: Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:05 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101179403.html>
{'area': u'\u71d5\u90ca \u798f\u6210\u4e94\u671f\u516c\u4ea4\u603b\u7ad9',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5546\u54c1\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u94a2\u6df7\u7ed3\u6784',
 'community': u'\u798f\u57ce\u4e0a\u4e0a\u57ce\u4e94\u671f',
 'elevator': u'\u6709',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u4f4e\u697c\u5c42 (\u517128\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'99.3\u33a1',
 'in_area': u'77.49\u33a1',
 'latitude': '116.85037,39.963617',
 'mortgage': u'\u6709\u62b5\u62bc',
 'orient': u'\u5357 \u5317',
 'price': u'270',
 'scale': u'\u4e24\u68af\u4e94\u6237',
 'status': u'\u7cbe\u88c5',
 'structure': u'\u5e73\u5c42',
 'style': u'2\u5ba41\u53851\u53a82\u536b',
 'tag': u'\u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-02-16',
 'trade': u'2009-10-08',
 'unit_price': u'27190',
 'url': 'http://bj.lianjia.com/ershoufang/101101179403.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:13:08 [scrapy] INFO: Crawled 12 pages (at 4 pages/min), scraped 11 items (at 4 items/min)
2017-05-12 17:13:08 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 200 http://bj.lianjia.com/ershoufang/101101352915.html
2017-05-12 17:13:08 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101352915.html> (referer: http://bj.lianjia.com/ershoufang/)
Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:08 [twisted] CRITICAL: Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:08 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101352915.html>
{'area': u'\u4e30\u53f0 \u5927\u7ea2\u95e8',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u4e00\u7c7b\u7ecf\u6d4e\u9002\u7528\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u7816\u6df7\u7ed3\u6784',
 'community': u'\u5efa\u6b23\u82d1\u4e8c\u91cc',
 'elevator': u'\u65e0',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u9876\u5c42 (\u51716\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'77.11\u33a1',
 'in_area': u'67.15\u33a1',
 'latitude': '116.402338,39.848564',
 'mortgage': u'\u65e0\u62b5\u62bc',
 'orient': u'\u5357 \u5317',
 'price': u'430',
 'scale': u'\u4e00\u68af\u4e24\u6237',
 'status': u'\u7cbe\u88c5',
 'structure': u'\u5e73\u5c42',
 'style': u'2\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u5730\u94c1 \u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-03-18',
 'trade': u'2006-08-18',
 'unit_price': u'55764',
 'url': 'http://bj.lianjia.com/ershoufang/101101352915.html',
 'warm': u'\u81ea\u4f9b\u6696'}
2017-05-12 17:13:11 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 200 http://bj.lianjia.com/ershoufang/101101545121.html
2017-05-12 17:13:11 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101545121.html> (referer: http://bj.lianjia.com/ershoufang/)
Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:11 [twisted] CRITICAL: Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:11 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101545121.html>
{'area': u'\u4e30\u53f0 \u65b9\u5e84',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5df2\u8d2d\u516c\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u5854\u697c',
 'building_style': u'\u94a2\u6df7\u7ed3\u6784',
 'community': u'\u82b3\u661f\u56ed\u4e09\u533a',
 'elevator': u'\u6709',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u4f4e\u697c\u5c42 (\u517118\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'63.32\u33a1',
 'in_area': u'\u6682\u65e0\u6570\u636e',
 'latitude': '116.441833,39.866749',
 'mortgage': u'\u65e0\u62b5\u62bc',
 'orient': u'\u5357 \u5317',
 'price': u'500',
 'scale': u'\u4e24\u68af\u516b\u6237',
 'status': u'\u7cbe\u88c5',
 'structure': u'\u6682\u65e0\u6570\u636e',
 'style': u'2\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u5730\u94c1 \u623f\u672c\u6ee1\u4e94\u5e74',
 'taxtext': '',
 'time': u'2017-05-04',
 'trade': u'2006-05-18',
 'unit_price': u'78964',
 'url': 'http://bj.lianjia.com/ershoufang/101101545121.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:13:15 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 200 http://bj.lianjia.com/ershoufang/pg2/
2017-05-12 17:13:15 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/pg2/> (referer: http://bj.lianjia.com/ershoufang/)
2017-05-12 17:13:15 [scrapy] DEBUG: Filtered duplicate request: <GET http://bj.lianjia.com/ershoufang/101101304930.html> - no more duplicates will be shown (see DUPEFILTER_DEBUG to show all duplicates)
2017-05-12 17:13:20 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 200 http://bj.lianjia.com/ershoufang/101101537313.html
2017-05-12 17:13:20 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101537313.html> (referer: http://bj.lianjia.com/ershoufang/)
Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:20 [twisted] CRITICAL: Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:20 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101537313.html>
{'area': u'\u671d\u9633 \u671b\u4eac',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5546\u54c1\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u7816\u6df7\u7ed3\u6784',
 'community': u'\u5357\u6e56\u4e2d\u56ed\u4e00\u533a',
 'elevator': u'\u65e0',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u4e2d\u697c\u5c42 (\u51717\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'70.79\u33a1',
 'in_area': u'54.55\u33a1',
 'latitude': '116.468477,40.008959',
 'mortgage': u'\u65e0\u62b5\u62bc',
 'orient': u'\u5357 \u5317',
 'price': u'565',
 'scale': u'\u4e00\u68af\u4e24\u6237',
 'status': u'\u7cbe\u88c5',
 'structure': u'\u5e73\u5c42',
 'style': u'2\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u5730\u94c1 \u623f\u672c\u6ee1\u4e94\u5e74',
 'taxtext': '',
 'time': u'2017-05-02',
 'trade': u'2002-06-27',
 'unit_price': u'79814',
 'url': 'http://bj.lianjia.com/ershoufang/101101537313.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:13:24 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 200 http://bj.lianjia.com/ershoufang/101101354577.html
2017-05-12 17:13:24 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101354577.html> (referer: http://bj.lianjia.com/ershoufang/)
Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:24 [twisted] CRITICAL: Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:24 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101354577.html>
{'area': u'\u71d5\u90ca \u798f\u6210\u4e94\u671f\u516c\u4ea4\u603b\u7ad9',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5546\u54c1\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u94a2\u6df7\u7ed3\u6784',
 'community': u'\u798f\u57ce\u4e0a\u4e0a\u57ce\u4e94\u671f',
 'elevator': u'\u6709',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u4f4e\u697c\u5c42 (\u517118\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'96.3\u33a1',
 'in_area': u'79.23\u33a1',
 'latitude': '116.85037,39.963617',
 'mortgage': u'\u6709\u62b5\u62bc 7\u4e07\u5143 \u5ba2\u6237\u507f\u8fd8',
 'orient': u'\u5357 \u5317',
 'price': u'265',
 'scale': u'\u4e24\u68af\u56db\u6237',
 'status': u'\u7cbe\u88c5',
 'structure': u'\u5e73\u5c42',
 'style': u'2\u5ba41\u53851\u53a82\u536b',
 'tag': u'\u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-03-18',
 'trade': u'2011-01-07',
 'unit_price': u'27518',
 'url': 'http://bj.lianjia.com/ershoufang/101101354577.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:13:28 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 200 http://bj.lianjia.com/ershoufang/101101304930.html
2017-05-12 17:13:28 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101304930.html> (referer: http://bj.lianjia.com/ershoufang/)
Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:28 [twisted] CRITICAL: Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:28 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101304930.html>
{'area': u'\u71d5\u90ca \u798f\u6210\u4e94\u671f\u516c\u4ea4\u603b\u7ad9',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5546\u54c1\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u94a2\u6df7\u7ed3\u6784',
 'community': u'\u798f\u57ce\u4e0a\u4e0a\u57ce\u4e94\u671f',
 'elevator': u'\u6709',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u4e2d\u697c\u5c42 (\u517128\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'99.73\u33a1',
 'in_area': u'78.15\u33a1',
 'latitude': '116.85037,39.963617',
 'mortgage': u'\u6709\u62b5\u62bc \u4e1a\u4e3b\u81ea\u8fd8',
 'orient': u'\u5357 \u5317',
 'price': u'270',
 'scale': u'\u4e24\u68af\u4e09\u6237',
 'status': u'\u7b80\u88c5',
 'structure': u'\u6682\u65e0\u6570\u636e',
 'style': u'2\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-03-09',
 'trade': u'2010-07-19',
 'unit_price': u'27073',
 'url': 'http://bj.lianjia.com/ershoufang/101101304930.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:13:31 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 200 http://bj.lianjia.com/ershoufang/101101173465.html
2017-05-12 17:13:31 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101173465.html> (referer: http://bj.lianjia.com/ershoufang/)
Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:32 [twisted] CRITICAL: Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:32 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101173465.html>
{'area': u'\u71d5\u90ca \u71d5\u987a\u8def\u56fd\u9053',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5546\u54c1\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u94a2\u6df7\u7ed3\u6784',
 'community': u'\u6f6e\u767d\u4eba\u5bb6',
 'elevator': u'\u6709',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u4e2d\u697c\u5c42 (\u517111\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'58.91\u33a1',
 'in_area': u'49.9\u33a1',
 'latitude': '116.797257,39.954145',
 'mortgage': u'\u6709\u62b5\u62bc \u4e1a\u4e3b\u81ea\u8fd8',
 'orient': u'\u5357',
 'price': u'200',
 'scale': u'\u4e00\u68af\u56db\u6237',
 'status': u'\u7b80\u88c5',
 'structure': u'\u6682\u65e0\u6570\u636e',
 'style': u'1\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-02-15',
 'trade': u'2012-04-10',
 'unit_price': u'33950',
 'url': 'http://bj.lianjia.com/ershoufang/101101173465.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:13:34 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 200 http://bj.lianjia.com/ershoufang/101101114188.html
2017-05-12 17:13:34 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101114188.html> (referer: http://bj.lianjia.com/ershoufang/)
Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:34 [twisted] CRITICAL: Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:34 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101114188.html>
{'area': u'\u71d5\u90ca \u798f\u6210\u4e94\u671f\u516c\u4ea4\u603b\u7ad9',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5546\u54c1\u623f',
 'belongs': u'\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u94a2\u6df7\u7ed3\u6784',
 'community': u'\u798f\u57ce\u4e0a\u4e0a\u57ce\u4e94\u671f',
 'elevator': u'\u6709',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u9ad8\u697c\u5c42 (\u517118\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'83.72\u33a1',
 'in_area': u'\u6682\u65e0\u6570\u636e',
 'latitude': '116.85037,39.963617',
 'mortgage': u'\u6682\u65e0\u6570\u636e',
 'orient': u'\u5357 \u5317',
 'price': u'190',
 'scale': u'\u4e24\u68af\u4e03\u6237',
 'status': u'\u6bdb\u576f',
 'structure': u'\u5e73\u5c42',
 'style': u'2\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-02-05',
 'trade': u'2010-07-27',
 'unit_price': u'22695',
 'url': 'http://bj.lianjia.com/ershoufang/101101114188.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:13:37 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 200 http://bj.lianjia.com/ershoufang/101101047743.html
2017-05-12 17:13:37 [scrapy] DEBUG: Crawled (200) <GET http://bj.lianjia.com/ershoufang/101101047743.html> (referer: http://bj.lianjia.com/ershoufang/)
Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:37 [twisted] CRITICAL: Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

2017-05-12 17:13:37 [scrapy] DEBUG: Scraped from <200 http://bj.lianjia.com/ershoufang/101101047743.html>
{'area': u'\u71d5\u90ca \u798f\u6210\u4e94\u671f\u516c\u4ea4\u603b\u7ad9',
 'backup': u'\u5df2\u4e0a\u4f20\u623f\u672c\u7167\u7247',
 'belong': u'\u5546\u54c1\u623f',
 'belongs': u'\u975e\u5171\u6709',
 'building': u'\u677f\u697c',
 'building_style': u'\u94a2\u6df7\u7ed3\u6784',
 'community': u'\u798f\u57ce\u4e0a\u4e0a\u57ce\u4e94\u671f',
 'elevator': u'\u6709',
 'exert': u'\u666e\u901a\u4f4f\u5b85',
 'fixed_year': u'70\u5e74',
 'floor': u'\u9ad8\u697c\u5c42 (\u517118\u5c42)',
 'house_fixed_year': u'\u6ee1\u4e94\u5e74',
 'housearea': u'79.82\u33a1',
 'in_area': u'60.04\u33a1',
 'latitude': '116.85037,39.963617',
 'mortgage': u'\u6709\u62b5\u62bc',
 'orient': u'\u5357 \u5317',
 'price': u'201',
 'scale': u'\u4e24\u68af\u516b\u6237',
 'status': u'\u7cbe\u88c5',
 'structure': u'\u5e73\u5c42',
 'style': u'2\u5ba41\u53851\u53a81\u536b',
 'tag': u'\u623f\u672c\u6ee1\u4e94\u5e74 \u968f\u65f6\u770b\u623f',
 'taxtext': '',
 'time': u'2017-01-07',
 'trade': u'2010-08-11',
 'unit_price': u'25182',
 'url': 'http://bj.lianjia.com/ershoufang/101101047743.html',
 'warm': u'\u96c6\u4e2d\u4f9b\u6696'}
2017-05-12 17:13:41 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 302 http://bj.lianjia.com/ershoufang/101101523851.html
2017-05-12 17:13:41 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:13:41 [lianjia.HttpProxyMiddleware] INFO: invalidate {'count': 29, 'valid': True, 'proxy': 'http://111.13.7.123:80'}
2017-05-12 17:13:41 [lianjia.HttpProxyMiddleware] INFO: now using new proxy: http://103.245.77.56:8080
2017-05-12 17:13:45 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 302 http://bj.lianjia.com/ershoufang/101101520656.html
2017-05-12 17:13:45 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:13:49 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 302 http://bj.lianjia.com/ershoufang/101101519442.html
2017-05-12 17:13:49 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
2017-05-12 17:13:52 [lianjia.HttpProxyMiddleware] DEBUG: http://111.13.7.123:80 302 http://bj.lianjia.com/ershoufang/101101466718.html
2017-05-12 17:13:52 [lianjia.HttpProxyMiddleware] INFO: response status not in spider.website_possible_httpstatus_list
